changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: "### {{.Kind}}"
changeFormat: "- {{.Body}}"
kinds:
  - label: Added
    auto: minor
  - label: Changed
    auto: minor
  - label: Fixed
    auto: patch
  - label: Security
    auto: patch
  - label: Internal
    auto: patch

newlines:
  beforeChangelogVersion: 1
  afterKind: 1
  beforeKind: 1
  endOfVersion: 1

# Replace version in VERSION file
replacements:
  - path: VERSION
    find: ".*"
    replace: "{{.VersionNoPrefix}}"

envPrefix: CHANGIE_
