[[mounts]]
source = 'pocketid_data'
destination = '/app/data'
initial_size = '1GB'

[http_service]
internal_port = 1411
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
