[build]

[[mounts]]
  source = 'data'
  destination = '/app/data'

[http_service]
  internal_port = 1411
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
